rule bet:
    input:
        t1w="data/sub-314/ses-BL/anat/sub-314_ses-BL_T1w.nii.gz",
    output:
        brain="out/bet/sub-314/ses-BL/anat/sub-314_ses-BL_desc-brain_T1w.nii.gz",
    shell:
        "bet {input} {output}"
